server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: postgres
    password: 1314
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발용: update, 운영용은 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
